// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXU4bTmdGHt6AEqMv6aldvLZbiOA0THew',
    appId: '1:596999773792:web:4b1354e2fa5a301edbad05',
    messagingSenderId: '596999773792',
    projectId: 'nomishop-a8712',
    authDomain: 'nomishop-a8712.firebaseapp.com',
    storageBucket: 'nomishop-a8712.appspot.com',
    measurementId: 'G-7NZ318VYHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1zHIV1ZQMz03X9LaJ3NuTvs7EakZYEJA',
    appId: '1:596999773792:android:8e1f9c7bca5700b2dbad05',
    messagingSenderId: '596999773792',
    projectId: 'nomishop-a8712',
    storageBucket: 'nomishop-a8712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDifEx3yafS3NTLXuwW07Fqz1Rbsbw6uyk',
    appId: '1:596999773792:ios:532a3caa03a3f2c4dbad05',
    messagingSenderId: '596999773792',
    projectId: 'nomishop-a8712',
    storageBucket: 'nomishop-a8712.appspot.com',
    iosBundleId: 'com.example.nomishop',
  );

}